### ISSUE TITLE
fontFit is undefined

### ISSUE THREAD

**Issue by anaran** [gaia-components/gaia-header#20]
I had this working three weeks ago in a fxos privileged app of mine.

Today I get this console.trace.

module.exports<.runFontFit() gaia-header.js:82
module.exports<.created() gaia-header.js:48
base<.createdCallback() gaia-component.js:57

I have run

bower install gaia-components/gaia-header
bower install gaia-components/gaia-fonts
bower install gaia-components/font-fit

today, but still get this error.

What did I miss?

**Comment by wilsonpage** [comment]
If you use the `dist/gaia-header.js` everything will just work as all the dependencies are bundled. Alternatively you can manage the dependencies yourself and do something like:

```html
<script src="bower_components/gaia-header/lib/font-fit.js"></script>
<script src="bower_components/gaia-header/gaia-header.js"></script>
```

**Comment by wilsonpage** [comment]
FYI web-components are only turned on for 'certified' (system) apps right now until platform devs are happy to make them available to the world.

**Comment by anaran** [comment]
Thanks for the quick response.

I went with
<script src="/bower_components/gaia-header/lib/font-fit.js"></script>
which works for me.
