### ISSUE TITLE
l10n-action nodes inside the header should not be measured

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/gaia-header#42]
This causes the title text to be incorrectly aligned.

**Comment by wilsonpage** [comment]
@julienw r?

**Comment by wilsonpage** [comment]
I also took this opportunity to update the syntax to use `l10n-action` attribute instead of a class. This is a somewhat establish convention and IMO stand out as more of an intent to distribute instead of a common class.

Also closer to the upcoming 'named slots' API that will replace `<content select=".foo">`.

**Comment by julienw** [comment]
reviewed on the PR https://github.com/gaia-components/gaia-header/pull/43
